version: '3.8'

services:
  api-server:
    # Use your Docker Hub image instead of building locally
    image: devdam16/register-button-api:latest
    # build: .  # Remove this line when using Docker Hub image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for additional security
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
